[package]
name = "sp-rust"
version = "0.1.0"
authors = ["xthexder"]
edition = "2021"

[profile.dev]
opt-level = 2

[dependencies]
cxx = "1.0"
wasmer = "2.1.1"
anyhow = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
